radius_restart_cmd = "/etc/init.d/utm5_radius stop && /etc/init.d/utm5_radius start"
session_life_time = "10m"           # TTL for RADIUS session

[utm]
api_url = "https://example.com/api/v1"      # UTM5 API url (https://github.com/sir-go/utm5-urfa-api)
prefix = ""                       # billing prefix (for urfa methods)
username = ""                       # billing system account name
password = ""                       # billing system account password

[ssh]                         # billing hosts (for API prefix and SSH connection)
address = ""
username = ""
password = ""
timeout = "1m"

[cisco]                                 # ISG-Router telnet credentials
address = ""
username = ""
password = ""
drop_sessions_cmd = "clear sss session user"
command_timeout = "10s"
